export const REQUEST_MEDICINE_REQUEST = 'REQUEST_MEDICINE_REQUEST'
export const REQUEST_MEDICINE_SUCCESS = 'REQUEST_MEDICINE_SUCCESS'
export const REQUEST_MEDICINE_FAIL = 'REQUEST_MEDICINE_FAIL'

export const DONATE_MEDICINE_REQUEST = 'DONATE_MEDICINE_REQUEST'
export const DONATE_MEDICINE_SUCCESS = 'DONATE_MEDICINE_SUCCESS'
export const DONATE_MEDICINE_FAIL = 'DONATE_MEDICINE_FAIL'

export const ALL_MEDICINES_REQUEST = 'ALL_MEDICINES_REQUEST'
export const ALL_MEDICINES_SUCCESS = 'ALL_MEDICINES_SUCCESS'
export const ALL_MEDICINES_FAIL = 'ALL_MEDICINES_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'