export const REQUEST_MEDICINE_REQUEST = 'ALL_PRODUCTS_REQUEST'
export const REQUEST_MEDICINE_SUCCESS = 'ALL_PRODUCTS_SUCCESS'
export const REQUEST_MEDICINE_FAIL = 'ALL_PRODUCTS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'